### ISSUE TITLE
Hls m3u8

### ISSUE THREAD

**Issue by trimechee** [o7q/MediaDownloader#1]
Hello, thank you very much for this wonderful downloader ! 

I have request please : many and many streams are in HLS m3u8 format, it will be great if MediaDowloader support these CLI software to donwload from even more web sites, thank you so much !

m3u8 : Python m3u8 Parser for HTTP Live Streaming (HLS) Transmissions :

https://github.com/globocom/m3u8

[.NET] m3u8 downloader Open source command line m3u8/HLS/dash downloader, supports common AES-128-CBC decryption, multi-threading, custom request headers, etc. Supports Simplified Chinese, Traditional Chinese and English. English Supported.

https://github.com/nilaoda/N_m3u8DL-CLI

C program to download VoD HLS (.m3u8) files

https://github.com/selsta/hlsdl

[.NET7] Cross-Platform stream downloader for DASH/HLS.

https://github.com/nilaoda/N_m3u8DL-RE

and

https://github.com/HeiSir2014/M3U8-Downloader

https://github.com/Spark-NF/hls-downloader

**Comment by o7q** [comment]
I will look into these, do not expect them to be added but I appreciate the ideas. :)

**Comment by trimechee** [comment]
Great  !! Thank you so much :)
