### ISSUE TITLE
Accelerators wget, aria2c, ffmpeg and new dowloaders engines you-get and lux and N_m3u8DL-CLI

### ISSUE THREAD

**Issue by trimechee** [o7q/MediaDownloader#2]
Hello, when we download dailymotion videos from for exemple  https://www.dailymotion.com/tpmp/videos , the speed of download is limited to only 48kb/s when we use yt-dlp, but when we use yt-dlp with aria2c and yt-dlp ffpmpeg with ffmpeg as downloader,  the download speed increase very much !
 it will be awesome if MediaDowloader can offers us a feature and an option with yt -dlp modified to use these accelerators ad downloader engine accelerator combined with yt-dlp , thank you vey much !

https://www.gnu.org/software/wget/

https://aria2.github.io/

https://github.com/yt-dlp/FFmpeg-Builds

There are also these CLI softwares that allow US to download many websites, it will be wonderful amazing if MediaDownloader can integrate them, thank you so much!

Dumb downloader that scrapes the web

https://github.com/soimort/you-get

Fast and simple video download library and CLI tool written in Go

https://github.com/iawia002/lux

and N_m3u8DL-CLI

https://github.com/nilaoda/N_m3u8DL-CLI

**Comment by o7q** [comment]
I will also look into these, again, do not expect them to be added. :)

**Comment by trimechee** [comment]
Awesome ! Thank you very much for your generosity :) 💯 i understand absolutely :) 👍  it was just suggestions because yt-dl was censored and even deleted from github following a dmca complaint so i offered these tools as a possible alternatives if yt-dlp stops working.... 
The awesome MediaDownloader is already beautiful and complete, thank you very much for this magnificent software one of the few with another software that I appreciate for its rare and unique features and options :)
