### ISSUE TITLE
Unable to use Sponsorblock

### ISSUE THREAD

**Issue by peppersgc** [o7q/MediaDownloader#3]
(please ensure you have exhausted all attempts at repairing the bug yourself before asking for help.)

**Describe the bug**
The box for custom arguments was removed making it impossible to use YT-DLP's Sponsorblock integration.

**To Reproduce**
1. Open MediaDownloader

**Expected behavior**
A box to input "sponsorblock-remove sponsor" into.

**Screenshots**
N/A
**Additional context**
None

**Comment by o7q** [comment]
Hello. I did not realize that the "Custom DL Arguments" option was actually being used. I originally implemented it for debugging so I assumed it was just taking up space. I will add it back in the next update, for now you can use v3.5.2 if you'd like, it still has that feature.

**Comment by peppersgc** [comment]
Thanks for the reply.

**Comment by o7q** [comment]
FYI: I have just released the new version of MediaDownloader that added back the custom arguments feature.
