### ISSUE TITLE
Protected streaming 

### ISSUE THREAD

**Issue by trimechee** [o7q/MediaDownloader#4]
Hello, recently i discover this disucussion in videohelp forum about donwload enrypted streams, ant it said :
 "No m3u8, but mpd.

Your stream is encrypted. You will need keys to decrypt.

yt-dlp --allow-u "mpd_url"

https://forum.videohelp.com/threads/407535-Zee5-video-download

Does MediaDonwloader include by default this command " --allow-u "mpd_url" to donwload encrypted streams please ? if not, how can we add by default this command "--allow-u" please ?

**Comment by o7q** [comment]
You can do this using the yt-dlp Arguments feature in the new v3.7.0 update.

**Comment by trimechee** [comment]
Awesome ! thank you very much :)
