### ISSUE TITLE
YTDL-patched 

### ISSUE THREAD

**Issue by trimechee** [o7q/MediaDownloader#5]
Hello, thank you again so much for these fantatic incredible software MediaDownloader !! 💯 

i have another suggestion please : i find new software : YTDL-patched =yt-dlp fork with some more features : keep merging with yt-dlp/yt-dlp
implement miscellaneous extractors as possible , make -U work (yes, really works)
do anything best, may be it will be good to add this downloader to MediaDownloader ! thank you :)

https://github.com/ytdl-patched/ytdl-patched

**Comment by o7q** [comment]
I will look into it.

**Comment by trimechee** [comment]
Fantastic ! Thank you so much !
