### ISSUE TITLE
No file name 

### ISSUE THREAD

**Issue by KalpanaChetan** [o7q/MediaDownloader#7]
![Screenshot (2).png](https://user-images.githubusercontent.com/112402936/201520743-0fff04ef-49e5-47d7-877f-ce09b4c192ec.png)

**Comment by KalpanaChetan** [comment]
![Screenshot (4).png](https://user-images.githubusercontent.com/112402936/201520922-74831735-66af-4041-abea-c8e157bbea0e.png)

**Comment by o7q** [comment]
You can specify a filename in the "Name" textbox.
