### ISSUE TITLE
Please add features 

### ISSUE THREAD

**Issue by KalpanaChetan** [o7q/MediaDownloader#8]
1.please add scheduler

2 .Playlist downloader

3.Download video from a playlist in this method
Create a folder (channel name) and create another folder (playlist name) inside it and a third folder (video number) inside it
Video has to be downloaded in third folder
Create a third folder (video number) for each video

**Comment by o7q** [comment]
Most of those features can be accessed through the `yt-dlp Arguments` option. Playlist support has also been implemented in recent versions of MediaDownloader.
